/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.staff;

import javax.swing.*;
import controller.Controller_Staff;
import java.time.format.*;
import java.time.*;
import model.Model;

/**
 *
 * @author ADMIN
 */
public class View_Staff_Add_Record extends javax.swing.JFrame {

    /**
     * Creates new form View_Staff_Entry
     */
    public View_Staff_Add_Record() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_Button = new javax.swing.JButton();
        airport_Label = new javax.swing.JLabel();
        airport_Field = new javax.swing.JTextField();
        airport_Id_Label = new javax.swing.JLabel();
        airport_Id_Field = new javax.swing.JTextField();
        flight_Label = new javax.swing.JLabel();
        flight_Field = new javax.swing.JTextField();
        airline_Label = new javax.swing.JLabel();
        airline_Field = new javax.swing.JTextField();
        gate_Label = new javax.swing.JLabel();
        gate_Spinner = new javax.swing.JSpinner();
        name_Label = new javax.swing.JLabel();
        name_Field = new javax.swing.JTextField();
        nation_Combobox = new javax.swing.JComboBox<>();
        nation_Label = new javax.swing.JLabel();
        dob_Label = new javax.swing.JLabel();
        dob_Day_Combobox = new javax.swing.JComboBox<>();
        dob_Month_Combobox = new javax.swing.JComboBox<>();
        dob_Year_Combobox = new javax.swing.JComboBox<>();
        sex_Label = new javax.swing.JLabel();
        check_Button = new javax.swing.JButton();
        isMale_Rbutton = new javax.swing.JRadioButton();
        accept_Button = new javax.swing.JButton();
        type_Label = new javax.swing.JLabel();
        type_Combobox = new javax.swing.JComboBox<>();
        customer_Label = new javax.swing.JLabel();
        cus_Type_Combobox = new javax.swing.JComboBox<>();
        reason_Label = new javax.swing.JLabel();
        reason_Field = new javax.swing.JTextField();
        stay_Label = new javax.swing.JLabel();
        stay_Spinner = new javax.swing.JSpinner();
        locate_Label = new javax.swing.JLabel();
        locate_Field = new javax.swing.JTextField();
        id_Card_Label = new javax.swing.JLabel();
        id_Card_Field = new javax.swing.JTextField();
        birth_Cert_Field = new javax.swing.JTextField();
        birth_Cert_Label = new javax.swing.JLabel();
        passport_Field = new javax.swing.JTextField();
        passport_Label = new javax.swing.JLabel();
        visa_Label = new javax.swing.JLabel();
        visa_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add record");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        back_Button.setText("Back");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        airport_Label.setText("Airport");

        airport_Id_Label.setText("Airport ID");

        flight_Label.setText("Flight");

        airline_Label.setText("Airline");

        gate_Label.setText("Gate");

        name_Label.setText("Name");

        nation_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
            "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "The Bahamas", "Bahrain",
            "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia",
            "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso",
            "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic",
            "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba",
            "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
            "Ecuador", "Egypt", "El Salvador", "England", "Equatorial Guinea", "Eritrea", "Estonia",
            "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "The Gambia", "Georgia",
            "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
            "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
            "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
            "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
            "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
            "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco",
            "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal",
            "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Northern Ireland", "North Macedonia", "Norway",
            "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
            "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
            "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Scotland",
            "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
            "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden",
            "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago",
            "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United States",
            "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Wales", "Yemen", "Zambia", "Zimbabwe"  }));
nation_Combobox.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        nation_ComboboxActionPerformed(evt);
    }
    });

    nation_Label.setText("Nation");

    dob_Label.setText("DoB");

    dob_Day_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 1; i <= 31; i++) {
        dob_Day_Combobox.addItem(String.format("%02d", i));
    }
    dob_Day_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dob_Day_ComboboxActionPerformed(evt);
        }
    });

    dob_Month_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 1; i <= 12; i++) {
        dob_Month_Combobox.addItem(String.format("%02d", i));
    }
    dob_Month_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dob_Month_ComboboxActionPerformed(evt);
        }
    });

    dob_Year_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 2024; i >= 1900; i--) {
        dob_Year_Combobox.addItem(String.format("%d", i));
    }
    dob_Year_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dob_Year_ComboboxActionPerformed(evt);
        }
    });

    sex_Label.setText("Sex");

    check_Button.setBackground(new java.awt.Color(255, 255, 153));
    check_Button.setText("Check");
    check_Button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            check_ButtonActionPerformed(evt);
        }
    });

    isMale_Rbutton.setText("is Male");
    isMale_Rbutton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            isMale_RbuttonActionPerformed(evt);
        }
    });

    accept_Button.setBackground(new java.awt.Color(0, 204, 51));
    accept_Button.setText("Accept");
    accept_Button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            accept_ButtonActionPerformed(evt);
        }
    });

    type_Label.setText("Type");

    type_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entry", "Exit" }));
    type_Combobox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            type_ComboboxItemStateChanged(evt);
        }
    });
    type_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            type_ComboboxActionPerformed(evt);
        }
    });

    customer_Label.setText("Customer");

    cus_Type_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domestic (ID card)", "Domestic (Birth cert)", "Foreign (Non Visa)", "Foreign (Visa)" }));
    cus_Type_Combobox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            cus_Type_ComboboxItemStateChanged(evt);
        }
    });

    reason_Label.setText("Reason");

    stay_Label.setText("Stay");

    stay_Spinner.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentHidden(java.awt.event.ComponentEvent evt) {
            stay_SpinnerComponentHidden(evt);
        }
        public void componentShown(java.awt.event.ComponentEvent evt) {
            stay_SpinnerComponentShown(evt);
        }
    });

    locate_Label.setText("Location");

    locate_Field.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentHidden(java.awt.event.ComponentEvent evt) {
            locate_FieldComponentHidden(evt);
        }
        public void componentShown(java.awt.event.ComponentEvent evt) {
            locate_FieldComponentShown(evt);
        }
    });

    id_Card_Label.setText("ID Card");

    id_Card_Field.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentHidden(java.awt.event.ComponentEvent evt) {
            id_Card_FieldComponentHidden(evt);
        }
        public void componentShown(java.awt.event.ComponentEvent evt) {
            id_Card_FieldComponentShown(evt);
        }
    });

    birth_Cert_Field.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentHidden(java.awt.event.ComponentEvent evt) {
            birth_Cert_FieldComponentHidden(evt);
        }
        public void componentShown(java.awt.event.ComponentEvent evt) {
            birth_Cert_FieldComponentShown(evt);
        }
    });

    birth_Cert_Label.setText("Birth cert");

    passport_Field.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentHidden(java.awt.event.ComponentEvent evt) {
            passport_FieldComponentHidden(evt);
        }
        public void componentShown(java.awt.event.ComponentEvent evt) {
            passport_FieldComponentShown(evt);
        }
    });

    passport_Label.setText("Passport");

    visa_Label.setText("Visa");

    visa_Field.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentHidden(java.awt.event.ComponentEvent evt) {
            visa_FieldComponentHidden(evt);
        }
        public void componentShown(java.awt.event.ComponentEvent evt) {
            visa_FieldComponentShown(evt);
        }
    });
    visa_Field.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            visa_FieldActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(back_Button)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(airport_Id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(airport_Id_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(flight_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(flight_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(gate_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(airline_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nation_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sex_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dob_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nation_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(airline_Field)
                                    .addComponent(gate_Spinner)
                                    .addComponent(name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(isMale_Rbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dob_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dob_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dob_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(airport_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customer_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(type_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(type_Combobox, 0, 200, Short.MAX_VALUE)
                                .addComponent(cus_Type_Combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(airport_Field))))
                    .addGap(55, 55, 55)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reason_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reason_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stay_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stay_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(locate_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(locate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(id_Card_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(id_Card_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(birth_Cert_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(birth_Cert_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(passport_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(passport_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(visa_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(visa_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(accept_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(check_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap(34, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(back_Button)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(reason_Field)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(type_Label)
                        .addComponent(type_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reason_Label))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customer_Label)
                        .addComponent(cus_Type_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(airport_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(airport_Label)
                .addComponent(stay_Label)
                .addComponent(stay_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airport_Id_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(airport_Id_Label)
                        .addComponent(locate_Label))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(flight_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(flight_Label)))
                .addComponent(locate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(airline_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(airline_Label)
                .addComponent(id_Card_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(id_Card_Label))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(birth_Cert_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(birth_Cert_Label)
                .addComponent(gate_Label)
                .addComponent(gate_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(passport_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(passport_Label)
                .addComponent(name_Label)
                .addComponent(name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nation_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nation_Label))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visa_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visa_Label)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(isMale_Rbutton)
                .addComponent(sex_Label))
            .addGap(13, 13, 13)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(accept_Button)
                .addComponent(check_Button)
                .addComponent(dob_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dob_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dob_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dob_Label))
            .addContainerGap(32, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void nation_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nation_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nation_ComboboxActionPerformed

    private void dob_Day_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_Day_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_Day_ComboboxActionPerformed

    private void dob_Month_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_Month_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_Month_ComboboxActionPerformed

    private void dob_Year_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_Year_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_Year_ComboboxActionPerformed

    private void check_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_ButtonActionPerformed
        // TODO add your handling code here:
        String dob = (String)dob_Year_Combobox.getSelectedItem()+"-"+(String)dob_Month_Combobox.getSelectedItem()+"-"+(String)dob_Day_Combobox.getSelectedItem();
        Controller_Staff.CheckInfo((String)type_Combobox.getSelectedItem(),(String)cus_Type_Combobox.getSelectedItem(), (int)gate_Spinner.getValue(), dob, (int)stay_Spinner.getValue(), (String)nation_Combobox.getSelectedItem(), passport_Field.getText());
        
    }//GEN-LAST:event_check_ButtonActionPerformed

    private void isMale_RbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isMale_RbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isMale_RbuttonActionPerformed

    private void accept_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_ButtonActionPerformed
        // TODO add your handling code here:
        LocalDateTime timeNow = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        // Chuyển chuỗi sang LocalDateTime
        String timeNowString = timeNow.format(formatter);
        
        String dob = (String)dob_Year_Combobox.getSelectedItem()+"-"+(String)dob_Month_Combobox.getSelectedItem()+"-"+(String)dob_Day_Combobox.getSelectedItem();
        if(Controller_Staff.CheckInfo((String)type_Combobox.getSelectedItem(),(String)cus_Type_Combobox.getSelectedItem(), (int)gate_Spinner.getValue(), dob, (int)stay_Spinner.getValue(), (String)nation_Combobox.getSelectedItem(), passport_Field.getText())==true){
            Model.saveRecord(timeNowString, (String)type_Combobox.getSelectedItem(), (String)cus_Type_Combobox.getSelectedItem(), 
                airport_Field.getText(), airport_Id_Field.getText(), flight_Field.getText(), airline_Field.getText(), 
                (int)gate_Spinner.getValue(), name_Field.getText(), (String) nation_Combobox.getSelectedItem(), dob, 
                isMale_Rbutton.isEnabled(), reason_Field.getText(), (int)stay_Spinner.getValue(), locate_Field.getText(), 
                id_Card_Field.getText(), birth_Cert_Field.getText(), passport_Field.getText(), visa_Field.getText());
        }
    }//GEN-LAST:event_accept_ButtonActionPerformed

    private void visa_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visa_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visa_FieldActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void stay_SpinnerComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_stay_SpinnerComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_stay_SpinnerComponentHidden

    private void stay_SpinnerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_stay_SpinnerComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_stay_SpinnerComponentShown

    private void locate_FieldComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_locate_FieldComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_locate_FieldComponentHidden

    private void locate_FieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_locate_FieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_locate_FieldComponentShown

    private void id_Card_FieldComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_id_Card_FieldComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_id_Card_FieldComponentHidden

    private void id_Card_FieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_id_Card_FieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_id_Card_FieldComponentShown

    private void birth_Cert_FieldComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_birth_Cert_FieldComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_Cert_FieldComponentHidden

    private void birth_Cert_FieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_birth_Cert_FieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_Cert_FieldComponentShown

    private void passport_FieldComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_passport_FieldComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_passport_FieldComponentHidden

    private void passport_FieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_passport_FieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_passport_FieldComponentShown

    private void visa_FieldComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_visa_FieldComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_visa_FieldComponentHidden

    private void visa_FieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_visa_FieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_visa_FieldComponentShown

    private void type_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_ComboboxActionPerformed

    private void type_ComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_type_ComboboxItemStateChanged
        // TODO add your handling code here:
        //Nhập cảnh quốc tế
        if(type_Combobox.getSelectedItem().equals("Entry")){
            if(cus_Type_Combobox.getSelectedItem().equals("Foreign (Non Visa)")){
                reason_Label.setVisible(true);
                reason_Field.setVisible(true);
                stay_Label.setText("Stay (Month)");
                stay_Label.setVisible(true);
                stay_Spinner.setVisible(true);
                locate_Label.setVisible(false);
                locate_Field.setVisible(false);
                id_Card_Label.setVisible(false);
                id_Card_Field.setVisible(false);
                birth_Cert_Label.setVisible(false);
                birth_Cert_Field.setVisible(false);
                passport_Label.setVisible(true);
                passport_Field.setVisible(true);
                visa_Label.setVisible(false);
                visa_Field.setVisible(false);
            }
            if(cus_Type_Combobox.getSelectedItem().equals("Foreign (Visa)")){
                reason_Label.setVisible(true);
                reason_Field.setVisible(true);
                stay_Label.setText("Stay (Day)");
                stay_Label.setVisible(true);
                stay_Spinner.setVisible(true);
                locate_Label.setVisible(true);
                locate_Field.setVisible(true);
                id_Card_Label.setVisible(false);
                id_Card_Field.setVisible(false);
                birth_Cert_Label.setVisible(false);
                birth_Cert_Field.setVisible(false);
                passport_Label.setVisible(true);
                passport_Field.setVisible(true);
                visa_Label.setVisible(true);
                visa_Field.setVisible(true);
            }
        }

        //Xuất cảnh quốc tế
        if(type_Combobox.getSelectedItem().equals("Exit")){
            if(cus_Type_Combobox.getSelectedItem().equals("Foreign (Non Visa)")){
                reason_Label.setVisible(false);
                reason_Field.setVisible(false);
                stay_Label.setVisible(false);
                stay_Spinner.setVisible(false);
                locate_Label.setVisible(false);
                locate_Field.setVisible(false);
                id_Card_Label.setVisible(false);
                id_Card_Field.setVisible(false);
                birth_Cert_Label.setVisible(false);
                birth_Cert_Field.setVisible(false);
                passport_Label.setVisible(true);
                passport_Field.setVisible(true);
                visa_Label.setVisible(false);
                visa_Field.setVisible(false);
            }
            if(cus_Type_Combobox.getSelectedItem().equals("Foreign (Visa)")){
                reason_Label.setVisible(false);
                reason_Field.setVisible(false);
                stay_Label.setVisible(false);
                stay_Spinner.setVisible(false);
                locate_Label.setVisible(false);
                locate_Field.setVisible(false);
                id_Card_Label.setVisible(false);
                id_Card_Field.setVisible(false);
                birth_Cert_Label.setVisible(false);
                birth_Cert_Field.setVisible(false);
                passport_Label.setVisible(true);
                passport_Field.setVisible(true);
                visa_Label.setVisible(true);
                visa_Field.setVisible(true);
            }
        }
    }//GEN-LAST:event_type_ComboboxItemStateChanged

    private void cus_Type_ComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cus_Type_ComboboxItemStateChanged
        // TODO add your handling code here:
        //Xuất nhập cảnh nội địa bằng CCCD
        if(cus_Type_Combobox.getSelectedItem().equals("Domestic (ID card)")){
            reason_Label.setVisible(false);
            reason_Field.setVisible(false);
            stay_Label.setVisible(false);
            stay_Spinner.setVisible(false);
            locate_Label.setVisible(false);
            locate_Field.setVisible(false);
            id_Card_Label.setVisible(true);
            id_Card_Field.setVisible(true);
            birth_Cert_Label.setVisible(false);
            birth_Cert_Field.setVisible(false);
            passport_Label.setVisible(false);
            passport_Field.setVisible(false);
            visa_Label.setVisible(false);
            visa_Field.setVisible(false);
        }
        
        //Xuất nhập cảnh nội địa bằng giấy khai sinh
        if(cus_Type_Combobox.getSelectedItem().equals("Domestic (Birth cert)")){
            reason_Label.setVisible(false);
            reason_Field.setVisible(false);
            stay_Label.setVisible(false);
            stay_Spinner.setVisible(false);
            locate_Label.setVisible(false);
            locate_Field.setVisible(false);
            id_Card_Label.setVisible(false);
            id_Card_Field.setVisible(false);
            birth_Cert_Label.setVisible(true);
            birth_Cert_Field.setVisible(true);
            passport_Label.setVisible(false);
            passport_Field.setVisible(false);
            visa_Label.setVisible(false);
            visa_Field.setVisible(false);
        }
        
        //Nhập cảnh quốc tế
        if(type_Combobox.getSelectedItem().equals("Entry")){
            if(cus_Type_Combobox.getSelectedItem().equals("Foreign (Non Visa)")){
                reason_Label.setVisible(true);
                reason_Field.setVisible(true);
                stay_Label.setText("Stay (Month)");
                stay_Label.setVisible(true);
                stay_Spinner.setVisible(true);
                locate_Label.setVisible(false);
                locate_Field.setVisible(false);
                id_Card_Label.setVisible(false);
                id_Card_Field.setVisible(false);
                birth_Cert_Label.setVisible(false);
                birth_Cert_Field.setVisible(false);
                passport_Label.setVisible(true);
                passport_Field.setVisible(true);
                visa_Label.setVisible(false);
                visa_Field.setVisible(false);
            }
            if(cus_Type_Combobox.getSelectedItem().equals("Foreign (Visa)")){
                reason_Label.setVisible(true);
                reason_Field.setVisible(true);
                stay_Label.setText("Stay (Day)");
                stay_Label.setVisible(true);
                stay_Spinner.setVisible(true);
                locate_Label.setVisible(true);
                locate_Field.setVisible(true);
                id_Card_Label.setVisible(false);
                id_Card_Field.setVisible(false);
                birth_Cert_Label.setVisible(false);
                birth_Cert_Field.setVisible(false);
                passport_Label.setVisible(true);
                passport_Field.setVisible(true);
                visa_Label.setVisible(true);
                visa_Field.setVisible(true);
            }
        }

        //Xuất cảnh quốc tế
        if(type_Combobox.getSelectedItem().equals("Exit")){
            if(cus_Type_Combobox.getSelectedItem().equals("Foreign (Non Visa)")){
                reason_Label.setVisible(false);
                reason_Field.setVisible(false);
                stay_Label.setVisible(false);
                stay_Spinner.setVisible(false);
                locate_Label.setVisible(false);
                locate_Field.setVisible(false);
                id_Card_Label.setVisible(false);
                id_Card_Field.setVisible(false);
                birth_Cert_Label.setVisible(false);
                birth_Cert_Field.setVisible(false);
                passport_Label.setVisible(true);
                passport_Field.setVisible(true);
                visa_Label.setVisible(false);
                visa_Field.setVisible(false);
            }
            if(cus_Type_Combobox.getSelectedItem().equals("Foreign (Visa)")){
                reason_Label.setVisible(false);
                reason_Field.setVisible(false);
                stay_Label.setVisible(false);
                stay_Spinner.setVisible(false);
                locate_Label.setVisible(false);
                locate_Field.setVisible(false);
                id_Card_Label.setVisible(false);
                id_Card_Field.setVisible(false);
                birth_Cert_Label.setVisible(false);
                birth_Cert_Field.setVisible(false);
                passport_Label.setVisible(true);
                passport_Field.setVisible(true);
                visa_Label.setVisible(true);
                visa_Field.setVisible(true);
            }
        }
    }//GEN-LAST:event_cus_Type_ComboboxItemStateChanged

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        // TODO add your handling code here:
        View_Staff.run();
        dispose();
    }//GEN-LAST:event_back_ButtonActionPerformed

    public void hideStart(){
        reason_Label.setVisible(false);
        reason_Field.setVisible(false);
        stay_Label.setVisible(false);
        stay_Spinner.setVisible(false);
        locate_Label.setVisible(false);
        locate_Field.setVisible(false);
        id_Card_Label.setVisible(true);
        id_Card_Field.setVisible(true);
        birth_Cert_Label.setVisible(false);
        birth_Cert_Field.setVisible(false);
        passport_Label.setVisible(false);
        passport_Field.setVisible(false);
        visa_Label.setVisible(false);
        visa_Field.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Staff_Add_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Staff_Add_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Staff_Add_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Staff_Add_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        run();
    }
    
    public static void run(){
        View_Staff_Add_Record frame = new View_Staff_Add_Record();
        frame.setVisible(true);
        frame.hideStart();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept_Button;
    private javax.swing.JTextField airline_Field;
    private javax.swing.JLabel airline_Label;
    private javax.swing.JTextField airport_Field;
    private javax.swing.JTextField airport_Id_Field;
    private javax.swing.JLabel airport_Id_Label;
    private javax.swing.JLabel airport_Label;
    private javax.swing.JButton back_Button;
    private javax.swing.JTextField birth_Cert_Field;
    private javax.swing.JLabel birth_Cert_Label;
    private javax.swing.JButton check_Button;
    private javax.swing.JComboBox<String> cus_Type_Combobox;
    private javax.swing.JLabel customer_Label;
    private javax.swing.JComboBox<String> dob_Day_Combobox;
    private javax.swing.JLabel dob_Label;
    private javax.swing.JComboBox<String> dob_Month_Combobox;
    private javax.swing.JComboBox<String> dob_Year_Combobox;
    private javax.swing.JTextField flight_Field;
    private javax.swing.JLabel flight_Label;
    private javax.swing.JLabel gate_Label;
    private javax.swing.JSpinner gate_Spinner;
    private javax.swing.JTextField id_Card_Field;
    private javax.swing.JLabel id_Card_Label;
    private javax.swing.JRadioButton isMale_Rbutton;
    private javax.swing.JTextField locate_Field;
    private javax.swing.JLabel locate_Label;
    private javax.swing.JTextField name_Field;
    private javax.swing.JLabel name_Label;
    private javax.swing.JComboBox<String> nation_Combobox;
    private javax.swing.JLabel nation_Label;
    private javax.swing.JTextField passport_Field;
    private javax.swing.JLabel passport_Label;
    private javax.swing.JTextField reason_Field;
    private javax.swing.JLabel reason_Label;
    private javax.swing.JLabel sex_Label;
    private javax.swing.JLabel stay_Label;
    private javax.swing.JSpinner stay_Spinner;
    private javax.swing.JComboBox<String> type_Combobox;
    private javax.swing.JLabel type_Label;
    private javax.swing.JTextField visa_Field;
    private javax.swing.JLabel visa_Label;
    // End of variables declaration//GEN-END:variables
}
