/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.staff;

/**
 *
 * @author ADMIN
 */
public class View_Passport extends javax.swing.JFrame {

    /**
     * Creates new form View_Passport
     */
    public View_Passport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scan_Button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        isMale_Rbutton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        code_Field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        type_Field = new javax.swing.JTextField();
        name_Field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nation_Combobox = new javax.swing.JComboBox<>();
        issue_Day_Combobox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        issue_Month_Combobox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        issue_Year_Combobox = new javax.swing.JComboBox<>();
        dob_Day_Combobox = new javax.swing.JComboBox<>();
        dob_Month_Combobox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        exp_Day_Combobox = new javax.swing.JComboBox<>();
        dob_Year_Combobox = new javax.swing.JComboBox<>();
        exp_Month_Combobox = new javax.swing.JComboBox<>();
        back_Button = new javax.swing.JButton();
        exp_Year_Combobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        id_Field = new javax.swing.JTextField();
        save_Button = new javax.swing.JButton();
        reset_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scan_Button.setText("Scan");
        scan_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scan_ButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Sex");

        isMale_Rbutton.setText("is Male");
        isMale_Rbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isMale_RbuttonActionPerformed(evt);
            }
        });

        jLabel10.setText("Code");

        jLabel11.setText("Type");

        jLabel6.setText("Name");

        type_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_FieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Issue date");

        nation_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
            "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "The Bahamas", "Bahrain",
            "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia",
            "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso",
            "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic",
            "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba",
            "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
            "Ecuador", "Egypt", "El Salvador", "England", "Equatorial Guinea", "Eritrea", "Estonia",
            "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "The Gambia", "Georgia",
            "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
            "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
            "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
            "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
            "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
            "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco",
            "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal",
            "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Northern Ireland", "North Macedonia", "Norway",
            "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
            "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
            "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Scotland",
            "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
            "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden",
            "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago",
            "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United States",
            "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Wales", "Yemen", "Zambia", "Zimbabwe"  }));
nation_Combobox.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        nation_ComboboxActionPerformed(evt);
    }
    });

    issue_Day_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 1; i <= 31; i++) {
        dob_Day_Combobox.addItem(String.format("%02d", i));
    }
    issue_Day_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            issue_Day_ComboboxActionPerformed(evt);
        }
    });

    jLabel7.setText("Nation");

    issue_Month_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 1; i <= 12; i++) {
        dob_Month_Combobox.addItem(String.format("%02d", i));
    }
    issue_Month_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            issue_Month_ComboboxActionPerformed(evt);
        }
    });

    jLabel8.setText("DoB");

    issue_Year_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 2024; i >= 1900; i--) {
        dob_Year_Combobox.addItem(String.format("%d", i));
    }
    issue_Year_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            issue_Year_ComboboxActionPerformed(evt);
        }
    });

    dob_Day_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 1; i <= 31; i++) {
        dob_Day_Combobox.addItem(String.format("%02d", i));
    }
    dob_Day_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dob_Day_ComboboxActionPerformed(evt);
        }
    });

    dob_Month_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 1; i <= 12; i++) {
        dob_Month_Combobox.addItem(String.format("%02d", i));
    }
    dob_Month_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dob_Month_ComboboxActionPerformed(evt);
        }
    });

    jLabel13.setText("Exp date");

    exp_Day_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 1; i <= 31; i++) {
        dob_Day_Combobox.addItem(String.format("%02d", i));
    }
    exp_Day_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            exp_Day_ComboboxActionPerformed(evt);
        }
    });

    dob_Year_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 2024; i >= 1900; i--) {
        dob_Year_Combobox.addItem(String.format("%d", i));
    }
    dob_Year_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dob_Year_ComboboxActionPerformed(evt);
        }
    });

    exp_Month_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 1; i <= 12; i++) {
        dob_Month_Combobox.addItem(String.format("%02d", i));
    }
    exp_Month_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            exp_Month_ComboboxActionPerformed(evt);
        }
    });

    back_Button.setText("Back");
    back_Button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            back_ButtonActionPerformed(evt);
        }
    });

    exp_Year_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (int i = 2024; i >= 1900; i--) {
        dob_Year_Combobox.addItem(String.format("%d", i));
    }
    exp_Year_Combobox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            exp_Year_ComboboxActionPerformed(evt);
        }
    });

    jLabel1.setText("ID");

    save_Button.setText("Save");
    save_Button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            save_ButtonActionPerformed(evt);
        }
    });

    reset_Button.setText("Reset");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(back_Button)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(isMale_Rbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nation_Combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name_Field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dob_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dob_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dob_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(id_Field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(code_Field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type_Field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(exp_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exp_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exp_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(issue_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(issue_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(issue_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scan_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save_Button))))
            .addContainerGap(31, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(back_Button)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(id_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dob_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dob_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dob_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(isMale_Rbutton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(nation_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(code_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(type_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(issue_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(issue_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(issue_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(exp_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(exp_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(exp_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel13))
            .addGap(17, 17, 17)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(save_Button)
                .addComponent(reset_Button)
                .addComponent(scan_Button))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scan_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scan_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scan_ButtonActionPerformed

    private void isMale_RbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isMale_RbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isMale_RbuttonActionPerformed

    private void type_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_FieldActionPerformed

    private void nation_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nation_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nation_ComboboxActionPerformed

    private void issue_Day_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_Day_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issue_Day_ComboboxActionPerformed

    private void issue_Month_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_Month_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issue_Month_ComboboxActionPerformed

    private void issue_Year_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_Year_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issue_Year_ComboboxActionPerformed

    private void dob_Day_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_Day_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_Day_ComboboxActionPerformed

    private void dob_Month_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_Month_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_Month_ComboboxActionPerformed

    private void exp_Day_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp_Day_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exp_Day_ComboboxActionPerformed

    private void dob_Year_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_Year_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_Year_ComboboxActionPerformed

    private void exp_Month_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp_Month_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exp_Month_ComboboxActionPerformed

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void exp_Year_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp_Year_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exp_Year_ComboboxActionPerformed

    private void save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Passport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Passport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Passport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Passport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Passport().setVisible(true);
            }
        });
    }
    
    public static void run(){
        new View_Passport().setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_Button;
    private javax.swing.JTextField code_Field;
    private javax.swing.JComboBox<String> dob_Day_Combobox;
    private javax.swing.JComboBox<String> dob_Month_Combobox;
    private javax.swing.JComboBox<String> dob_Year_Combobox;
    private javax.swing.JComboBox<String> exp_Day_Combobox;
    private javax.swing.JComboBox<String> exp_Month_Combobox;
    private javax.swing.JComboBox<String> exp_Year_Combobox;
    private javax.swing.JTextField id_Field;
    private javax.swing.JRadioButton isMale_Rbutton;
    private javax.swing.JComboBox<String> issue_Day_Combobox;
    private javax.swing.JComboBox<String> issue_Month_Combobox;
    private javax.swing.JComboBox<String> issue_Year_Combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name_Field;
    private javax.swing.JComboBox<String> nation_Combobox;
    private javax.swing.JButton reset_Button;
    private javax.swing.JButton save_Button;
    private javax.swing.JButton scan_Button;
    private javax.swing.JTextField type_Field;
    // End of variables declaration//GEN-END:variables
}
