/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.manager;

import javax.swing.table.DefaultTableModel;
import model.Model;

/**
 *
 * @author ADMIN
 */
public class View_Filter_Record extends javax.swing.JFrame {
    private static DefaultTableModel model;
    /**
     * Creates new form View_Choose_Filter_Record
     */
    public View_Filter_Record() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_Button = new javax.swing.JButton();
        update_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        record_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Record");

        back_Button.setText("Back");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        update_Button.setText("Update");
        update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ButtonActionPerformed(evt);
            }
        });

        record_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Type", "Customer type", "Airport", "Airport ID", "Flight", "Airline", "Gate", "Name", "Nation", "Birthday", "Male", "Reason", "Stay", "Location", "ID Card", "Birth cert", "Passport", "Visa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(record_Table);
        if (record_Table.getColumnModel().getColumnCount() > 0) {
            record_Table.getColumnModel().getColumn(0).setResizable(false);
            record_Table.getColumnModel().getColumn(1).setResizable(false);
            record_Table.getColumnModel().getColumn(2).setResizable(false);
            record_Table.getColumnModel().getColumn(3).setResizable(false);
            record_Table.getColumnModel().getColumn(4).setResizable(false);
            record_Table.getColumnModel().getColumn(5).setResizable(false);
            record_Table.getColumnModel().getColumn(6).setResizable(false);
            record_Table.getColumnModel().getColumn(7).setResizable(false);
            record_Table.getColumnModel().getColumn(8).setResizable(false);
            record_Table.getColumnModel().getColumn(9).setResizable(false);
            record_Table.getColumnModel().getColumn(10).setResizable(false);
            record_Table.getColumnModel().getColumn(11).setResizable(false);
            record_Table.getColumnModel().getColumn(12).setResizable(false);
            record_Table.getColumnModel().getColumn(13).setResizable(false);
            record_Table.getColumnModel().getColumn(15).setResizable(false);
            record_Table.getColumnModel().getColumn(16).setResizable(false);
            record_Table.getColumnModel().getColumn(17).setResizable(false);
            record_Table.getColumnModel().getColumn(18).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1845, Short.MAX_VALUE)
                            .addComponent(update_Button))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back_Button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(back_Button)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(update_Button)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        // TODO add your handling code here:
        View_Manager.run();
        dispose();
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ButtonActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        model = Model.load_Record_Data(model);
        record_Table.setModel(model); // Cập nhật model của bảng

    }//GEN-LAST:event_update_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Filter_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Filter_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Filter_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Filter_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        run();
    }
    
    public static void run() {
        new View_Filter_Record().setVisible(true);
        model  = new DefaultTableModel(new Object[][] {}, new String[] {"Time", "Type", "Customer type", "Airport", "Airport ID", "Flight",
                                                                        "Airline", "Gate", "Name", "Nation", "Birthday", "Male", "Reason",
                                                                        "Stay time", "Locations", "ID Card", "Birth cert", "Passport", "Visa"});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_Button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable record_Table;
    private javax.swing.JButton update_Button;
    // End of variables declaration//GEN-END:variables
}
