/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.manager;

import controller.Controller_Manager;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import model.Model;

/**
 *
 * @author ADMIN
 */
public class View_Filter_Record extends javax.swing.JFrame {
    private static DefaultTableModel model;
    private static LocalDateTime fromDate;
    private static LocalDateTime toDate;
    /**
     * Creates new form View_Choose_Filter_Record
     */
    public View_Filter_Record() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_Button = new javax.swing.JButton();
        update_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        record_Table = new javax.swing.JTable();
        from_Day_Combobox = new javax.swing.JComboBox<>();
        from_Month_Combobox = new javax.swing.JComboBox<>();
        from_Year_Combobox = new javax.swing.JComboBox<>();
        from_Label = new javax.swing.JLabel();
        to_Label = new javax.swing.JLabel();
        to_Day_Combobox = new javax.swing.JComboBox<>();
        to_Month_Combobox = new javax.swing.JComboBox<>();
        to_Year_Combobox = new javax.swing.JComboBox<>();
        filter_Button = new javax.swing.JButton();
        type_Label = new javax.swing.JLabel();
        type_Entry_Checkbox = new javax.swing.JCheckBox();
        type_Exit_Checkbox = new javax.swing.JCheckBox();
        customer_Type_Label = new javax.swing.JLabel();
        cusType_Id_Card_Checkbox = new javax.swing.JCheckBox();
        cusType_Birth_Cert_Checkbox = new javax.swing.JCheckBox();
        cusType_Non_Visa_Checkbox = new javax.swing.JCheckBox();
        cusType_Visa_Checkbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Record");

        back_Button.setText("Back");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        update_Button.setText("See all");
        update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ButtonActionPerformed(evt);
            }
        });

        record_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Type", "Customer type", "Airport", "Airport ID", "Flight", "Airline", "Gate", "Name", "Nation", "Birthday", "Male", "Reason", "Stay time", "Locations", "ID Card", "Birth cert", "Passport", "Visa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(record_Table);
        if (record_Table.getColumnModel().getColumnCount() > 0) {
            record_Table.getColumnModel().getColumn(0).setResizable(false);
            record_Table.getColumnModel().getColumn(1).setResizable(false);
            record_Table.getColumnModel().getColumn(2).setResizable(false);
            record_Table.getColumnModel().getColumn(3).setResizable(false);
            record_Table.getColumnModel().getColumn(4).setResizable(false);
            record_Table.getColumnModel().getColumn(5).setResizable(false);
            record_Table.getColumnModel().getColumn(6).setResizable(false);
            record_Table.getColumnModel().getColumn(7).setResizable(false);
            record_Table.getColumnModel().getColumn(8).setResizable(false);
            record_Table.getColumnModel().getColumn(9).setResizable(false);
            record_Table.getColumnModel().getColumn(10).setResizable(false);
            record_Table.getColumnModel().getColumn(11).setResizable(false);
            record_Table.getColumnModel().getColumn(12).setResizable(false);
            record_Table.getColumnModel().getColumn(13).setResizable(false);
            record_Table.getColumnModel().getColumn(14).setResizable(false);
            record_Table.getColumnModel().getColumn(15).setResizable(false);
            record_Table.getColumnModel().getColumn(16).setResizable(false);
            record_Table.getColumnModel().getColumn(17).setResizable(false);
            record_Table.getColumnModel().getColumn(18).setResizable(false);
        }

        from_Day_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for (int i = 1; i <= 31; i++) {
            from_Day_Combobox.addItem(String.format("%02d", i));
        }
        from_Day_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_Day_ComboboxActionPerformed(evt);
            }
        });

        from_Month_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for (int i = 1; i <= 12; i++) {
            from_Month_Combobox.addItem(String.format("%02d", i));
        }
        from_Month_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_Month_ComboboxActionPerformed(evt);
            }
        });

        from_Year_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for (int i = 2024; i >= 1900; i--) {
            from_Year_Combobox.addItem(String.format("%d", i));
        }
        from_Year_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_Year_ComboboxActionPerformed(evt);
            }
        });

        from_Label.setText("From");

        to_Label.setText("to");

        to_Day_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for (int i = 1; i <= 31; i++) {
            to_Day_Combobox.addItem(String.format("%02d", i));
        }
        to_Day_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_Day_ComboboxActionPerformed(evt);
            }
        });

        to_Month_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for (int i = 1; i <= 12; i++) {
            to_Month_Combobox.addItem(String.format("%02d", i));
        }
        to_Month_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_Month_ComboboxActionPerformed(evt);
            }
        });

        to_Year_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for (int i = 2030; i >= 1900; i--) {
            to_Year_Combobox.addItem(String.format("%d", i));
        }
        to_Year_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_Year_ComboboxActionPerformed(evt);
            }
        });

        filter_Button.setText("Filter");
        filter_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_ButtonActionPerformed(evt);
            }
        });

        type_Label.setText("Type");

        type_Entry_Checkbox.setText("Entry");

        type_Exit_Checkbox.setText("Exit");

        customer_Type_Label.setText("Customer type");

        cusType_Id_Card_Checkbox.setText("Domestic (ID card)");
        cusType_Id_Card_Checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusType_Id_Card_CheckboxActionPerformed(evt);
            }
        });

        cusType_Birth_Cert_Checkbox.setText("Domestic (Birth cert)");

        cusType_Non_Visa_Checkbox.setText("Foreign (Non Visa)");
        cusType_Non_Visa_Checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusType_Non_Visa_CheckboxActionPerformed(evt);
            }
        });

        cusType_Visa_Checkbox.setText("Foreign (Visa)");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Records");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1600, Short.MAX_VALUE)
                        .addComponent(filter_Button)
                        .addGap(18, 18, 18)
                        .addComponent(update_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(type_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(type_Entry_Checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(type_Exit_Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(from_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(from_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(from_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(from_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(to_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(to_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(to_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(to_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102)
                                        .addComponent(customer_Type_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cusType_Non_Visa_Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cusType_Visa_Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cusType_Id_Card_Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cusType_Birth_Cert_Checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(back_Button)
                                        .addGap(484, 484, 484)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_Button))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from_Label)
                    .addComponent(from_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_Label)
                    .addComponent(to_Day_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_Month_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to_Year_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer_Type_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusType_Id_Card_Checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cusType_Birth_Cert_Checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cusType_Non_Visa_Checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cusType_Visa_Checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(type_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(type_Entry_Checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(type_Exit_Checkbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_Button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        // TODO add your handling code here:
        View_Manager.run();
        dispose();
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ButtonActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        model = Model.load_Record_Data(model);
        record_Table.setModel(model); // Cập nhật model của bảng

    }//GEN-LAST:event_update_ButtonActionPerformed

    private void from_Day_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_Day_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_Day_ComboboxActionPerformed

    private void from_Month_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_Month_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_Month_ComboboxActionPerformed

    private void from_Year_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_Year_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_Year_ComboboxActionPerformed

    private void to_Day_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_Day_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_Day_ComboboxActionPerformed

    private void to_Month_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_Month_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_Month_ComboboxActionPerformed

    private void to_Year_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_Year_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_Year_ComboboxActionPerformed

    private void filter_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_ButtonActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String strFromDate = (String)from_Year_Combobox.getSelectedItem()+"-"+(String)from_Month_Combobox.getSelectedItem()+"-"+(String)from_Day_Combobox.getSelectedItem()+" 00:00:00";
        String strToDate = (String)to_Year_Combobox.getSelectedItem()+"-"+(String)to_Month_Combobox.getSelectedItem()+"-"+(String)to_Day_Combobox.getSelectedItem()+" 00:00:00";
        fromDate = LocalDateTime.parse(strFromDate, formatter);
        toDate = LocalDateTime.parse(strToDate, formatter);
        model.setRowCount(0);
        model = Model.load_Record_Data(model);
        model = Controller_Manager.load_Filter_Record_Data(model,fromDate,toDate,type_Entry_Checkbox.isSelected(),type_Exit_Checkbox.isSelected(),
                                                            cusType_Id_Card_Checkbox.isSelected(),cusType_Birth_Cert_Checkbox.isSelected(),
                                                            cusType_Non_Visa_Checkbox.isSelected(),cusType_Visa_Checkbox.isSelected());
        record_Table.setModel(model);
    }//GEN-LAST:event_filter_ButtonActionPerformed

    private void cusType_Id_Card_CheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusType_Id_Card_CheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusType_Id_Card_CheckboxActionPerformed

    private void cusType_Non_Visa_CheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusType_Non_Visa_CheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusType_Non_Visa_CheckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Filter_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Filter_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Filter_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Filter_Record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        run();
    }
    
    public static void run() {
        new View_Filter_Record().setVisible(true);
        model  = new DefaultTableModel(new Object[][] {}, new String[] {"Time", "Type", "Customer type", "Airport", "Airport ID", "Flight",
                                                                        "Airline", "Gate", "Name", "Nation", "Birthday", "Male", "Reason",
                                                                        "Stay time", "Locations", "ID Card", "Birth cert", "Passport", "Visa"});
        type_Entry_Checkbox.setSelected(true);
        type_Exit_Checkbox.setSelected(true);
        cusType_Birth_Cert_Checkbox.setSelected(true);
        cusType_Id_Card_Checkbox.setSelected(true);
        cusType_Non_Visa_Checkbox.setSelected(true);
        cusType_Visa_Checkbox.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_Button;
    private static javax.swing.JCheckBox cusType_Birth_Cert_Checkbox;
    private static javax.swing.JCheckBox cusType_Id_Card_Checkbox;
    private static javax.swing.JCheckBox cusType_Non_Visa_Checkbox;
    private static javax.swing.JCheckBox cusType_Visa_Checkbox;
    private javax.swing.JLabel customer_Type_Label;
    private javax.swing.JButton filter_Button;
    private javax.swing.JComboBox<String> from_Day_Combobox;
    private javax.swing.JLabel from_Label;
    private javax.swing.JComboBox<String> from_Month_Combobox;
    private javax.swing.JComboBox<String> from_Year_Combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable record_Table;
    private javax.swing.JComboBox<String> to_Day_Combobox;
    private javax.swing.JLabel to_Label;
    private javax.swing.JComboBox<String> to_Month_Combobox;
    private javax.swing.JComboBox<String> to_Year_Combobox;
    private static javax.swing.JCheckBox type_Entry_Checkbox;
    private static javax.swing.JCheckBox type_Exit_Checkbox;
    private javax.swing.JLabel type_Label;
    private javax.swing.JButton update_Button;
    // End of variables declaration//GEN-END:variables
}
