package view.manager;

import javax.swing.JOptionPane;
import view.View_Login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author admin
 */
public class View_Manager extends javax.swing.JFrame {

    /**
     * Creates new form QuanLy
     */
    public View_Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staff_List_Button = new javax.swing.JButton();
        wanted_Button = new javax.swing.JButton();
        change_Password_Button = new javax.swing.JButton();
        log_Out_Button = new javax.swing.JButton();
        expried_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý");

        staff_List_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        staff_List_Button.setText("Staff list");
        staff_List_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_List_ButtonActionPerformed(evt);
            }
        });

        wanted_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        wanted_Button.setText("Wanted people list");
        wanted_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wanted_ButtonActionPerformed(evt);
            }
        });

        change_Password_Button.setText("Change password");

        log_Out_Button.setText("Log out");
        log_Out_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_Out_ButtonActionPerformed(evt);
            }
        });

        expried_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        expried_Button.setText("Expired people list");
        expried_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expried_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(change_Password_Button)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(log_Out_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staff_List_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wanted_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(expried_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(log_Out_Button)
                .addGap(58, 58, 58)
                .addComponent(staff_List_Button)
                .addGap(34, 34, 34)
                .addComponent(wanted_Button)
                .addGap(40, 40, 40)
                .addComponent(expried_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(change_Password_Button)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staff_List_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_List_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_List_ButtonActionPerformed

    private void wanted_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wanted_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wanted_ButtonActionPerformed

    private void expried_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expried_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expried_ButtonActionPerformed

    private void log_Out_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_Out_ButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this,"Do you want to log out?", "Log out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            View_Login.run();
            dispose(); // Đóng cửa sổ hiện tại
        }
    }//GEN-LAST:event_log_Out_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Manager().setVisible(true);
            }
        });
    }
    
    public static void run() {
        new View_Manager().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_Password_Button;
    private javax.swing.JButton expried_Button;
    private javax.swing.JButton log_Out_Button;
    private javax.swing.JButton staff_List_Button;
    private javax.swing.JButton wanted_Button;
    // End of variables declaration//GEN-END:variables
}
