package view.manager;

import view.Expired_Frame;
import controller.Controller;
import entity.Expired_Person;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Model;
import view.View_Login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author admin
 */
public class View_Manager extends javax.swing.JFrame {
    /**
     * Creates new form QuanLy
     */
    public View_Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staff_List_Button = new javax.swing.JButton();
        wanted_Button = new javax.swing.JButton();
        change_Password_Button = new javax.swing.JButton();
        log_Out_Button = new javax.swing.JButton();
        expried_Button = new javax.swing.JButton();
        name_Label = new javax.swing.JLabel();
        temp_Name_Field = new javax.swing.JLabel();
        id_Label = new javax.swing.JLabel();
        temp_Id_Label = new javax.swing.JLabel();
        record_Button = new javax.swing.JButton();
        record_Path_Button = new javax.swing.JButton();
        staff_Path_button = new javax.swing.JButton();
        wanted_Path_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Homepage");

        staff_List_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        staff_List_Button.setText("Staff list");
        staff_List_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_List_ButtonActionPerformed(evt);
            }
        });

        wanted_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        wanted_Button.setText("Wanted people list");
        wanted_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wanted_ButtonActionPerformed(evt);
            }
        });

        change_Password_Button.setText("Change password");
        change_Password_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_Password_ButtonActionPerformed(evt);
            }
        });

        log_Out_Button.setText("Log out");
        log_Out_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_Out_ButtonActionPerformed(evt);
            }
        });

        expried_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        expried_Button.setText("Expired people list");
        expried_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expried_ButtonActionPerformed(evt);
            }
        });

        name_Label.setText("Name:");

        temp_Name_Field.setText(Controller.getName());

        id_Label.setText("ID:");

        temp_Id_Label.setText(Controller.getTemp_Id());

        record_Button.setText("Records");
        record_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                record_ButtonActionPerformed(evt);
            }
        });

        record_Path_Button.setText("Record path");
        record_Path_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                record_Path_ButtonActionPerformed(evt);
            }
        });

        staff_Path_button.setText("Staff path");
        staff_Path_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_Path_buttonActionPerformed(evt);
            }
        });

        wanted_Path_Button.setText("Wanted path");
        wanted_Path_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wanted_Path_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(record_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(expried_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(id_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(temp_Id_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(temp_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(wanted_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(staff_List_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(change_Password_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(log_Out_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wanted_Path_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staff_Path_button, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(record_Path_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log_Out_Button)
                    .addComponent(record_Path_Button)
                    .addComponent(staff_Path_button)
                    .addComponent(wanted_Path_Button))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_Label)
                    .addComponent(temp_Id_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_Label)
                    .addComponent(temp_Name_Field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(record_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staff_List_Button)
                .addGap(13, 13, 13)
                .addComponent(wanted_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(expried_Button)
                .addGap(27, 27, 27)
                .addComponent(change_Password_Button)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staff_List_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_List_ButtonActionPerformed
        // TODO add your handling code here:
        View_Manager_Staff_List.run();
        dispose();
    }//GEN-LAST:event_staff_List_ButtonActionPerformed

    private void wanted_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wanted_ButtonActionPerformed
        // TODO add your handling code here:
        View_Manager_Wanted_List.run();
        dispose();
    }//GEN-LAST:event_wanted_ButtonActionPerformed

    private void expried_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expried_ButtonActionPerformed
        // TODO add your handling code here:
        List<Expired_Person> expired_People = Model.getOverdueEntries(); // Lấy danh sách đối tượng quá hạn
        Expired_Frame.displayExpiredPeople(expired_People);

    }//GEN-LAST:event_expried_ButtonActionPerformed

    private void log_Out_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_Out_ButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this,"Do you want to log out?", "Log out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            View_Login.run();
            dispose(); // Đóng cửa sổ hiện tại
        }
    }//GEN-LAST:event_log_Out_ButtonActionPerformed

    private void record_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_record_ButtonActionPerformed
        // TODO add your handling code here:
        View_Filter_Record.run();
        dispose();
    }//GEN-LAST:event_record_ButtonActionPerformed

    private void change_Password_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_Password_ButtonActionPerformed
        // TODO add your handling code here:
        View_Manager_Change_Password.run();
    }//GEN-LAST:event_change_Password_ButtonActionPerformed

    private void record_Path_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_record_Path_ButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        
        // Tùy chọn: Cho phép chọn nhiều tệp hoặc một tệp
        fileChooser.setMultiSelectionEnabled(false);  // Chỉ chọn một tệp

        // Thiết lập tiêu đề cho hộp thoại chọn tệp
        fileChooser.setDialogTitle("Chọn tệp CSV");

        // Hiển thị hộp thoại và chờ người dùng chọn
        int result = fileChooser.showOpenDialog(null);
        
        // Nếu người dùng nhấn "Open" thì lấy đường dẫn tệp đã chọn
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();  // Lấy đường dẫn tuyệt đối của tệp
            Model.setRecord_Path(filePath);
            
        } else {
            JOptionPane.showMessageDialog(null, "This file is not suitable", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_record_Path_ButtonActionPerformed

    private void staff_Path_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_Path_buttonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        
        // Tùy chọn: Cho phép chọn nhiều tệp hoặc một tệp
        fileChooser.setMultiSelectionEnabled(false);  // Chỉ chọn một tệp

        // Thiết lập tiêu đề cho hộp thoại chọn tệp
        fileChooser.setDialogTitle("Chọn tệp CSV");

        // Hiển thị hộp thoại và chờ người dùng chọn
        int result = fileChooser.showOpenDialog(null);
        
        // Nếu người dùng nhấn "Open" thì lấy đường dẫn tệp đã chọn
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();  // Lấy đường dẫn tuyệt đối của tệp
            Model.setUser_Path(filePath);
            
        } else {
            JOptionPane.showMessageDialog(null, "This file is not suitable", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_staff_Path_buttonActionPerformed

    private void wanted_Path_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wanted_Path_ButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        
        // Tùy chọn: Cho phép chọn nhiều tệp hoặc một tệp
        fileChooser.setMultiSelectionEnabled(false);  // Chỉ chọn một tệp

        // Thiết lập tiêu đề cho hộp thoại chọn tệp
        fileChooser.setDialogTitle("Chọn tệp CSV");

        // Hiển thị hộp thoại và chờ người dùng chọn
        int result = fileChooser.showOpenDialog(null);
        
        // Nếu người dùng nhấn "Open" thì lấy đường dẫn tệp đã chọn
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();  // Lấy đường dẫn tuyệt đối của tệp
            Model.setWanted_Path(filePath);
            
        } else {
            JOptionPane.showMessageDialog(null, "This file is not suitable", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_wanted_Path_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        run();
    }
    
    public static void run() {
        new View_Manager().setVisible(true);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_Password_Button;
    private javax.swing.JButton expried_Button;
    private javax.swing.JLabel id_Label;
    private javax.swing.JButton log_Out_Button;
    private javax.swing.JLabel name_Label;
    private javax.swing.JButton record_Button;
    private javax.swing.JButton record_Path_Button;
    private javax.swing.JButton staff_List_Button;
    private javax.swing.JButton staff_Path_button;
    private javax.swing.JLabel temp_Id_Label;
    private javax.swing.JLabel temp_Name_Field;
    private javax.swing.JButton wanted_Button;
    private javax.swing.JButton wanted_Path_Button;
    // End of variables declaration//GEN-END:variables
}
